import React, { useCallback, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BookOpen, Check, CheckCheck, ChevronLeft, ChevronRight, Download, ExternalLink, FlaskConical, Layers3, ListFilter, LoaderCircle, RefreshCw, Search, SlidersHorizontal, X } from 'lucide-react';
import SemanticView from './SemanticView';
import './base.css';
import './style.css';

type ReviewStatus='pending'|'accepted'|'rejected';
type Doc={id:string;title:string;word_count:number;characters:number;source_url:string;edition:string;license:string};
type Parallel={id:string;document_a:string;document_b:string;title_a:string;title_b:string;score:number;kind:'exact'|'near';words_a:number;words_b:number;status:ReviewStatus;note:string;excerpt_a:string;start_a:number;end_a:number;start_b:number;end_b:number;edit_distance:number;raw_exact:boolean;method:string;alignment_score:number|null};
type Passage={title:string;reference:string;text:string;before:string;after:string;start:number;end:number;source_url:string};
type Detail=Parallel & {passages:Passage[];diff:{kind:string;a:[number,number];b:[number,number]}[]};
type Stats={counts:Record<string,number>;algorithm:string;progress:{running:boolean;completed_pairs:number;total_pairs:number};run:null|{id:number;status:string;duration_seconds:number;started_at:string;error:string;config:Record<string,number>;pairs:{document_a:string;document_b:string;matches:number;candidate_windows:number;seeds:number;contiguous_seeds:number;skip_seeds:number;duration_seconds:number}[]}};
const initialFilters={document:'',pair:'',kind:'',status:'',min_score:'0',min_words:'0',q:'',sort:'score'};
async function api<T>(url:string,options?:RequestInit):Promise<T>{const r=await fetch(url,options);if(!r.ok){let message=`Request failed (${r.status})`;try{const body=await r.json();if(typeof body.detail==='string')message=body.detail}catch{/* retain status */}throw new Error(message)}return r.json()}
const percent=(v:number)=>(v*100).toFixed(1)+'%';
function Badge({kind}:{kind:string}){return <span className={`badge ${kind}`}>{kind==='near'?'Near match':kind==='exact'?'Exact match':kind[0].toUpperCase()+kind.slice(1)}</span>}
function PassageView({passage,diff,side,changes}:{passage:Passage;diff:Detail['diff'];side:'a'|'b';changes:boolean}){
 const chars=Array.from(passage.text);let cursor=0;const fragments:React.ReactNode[]=[];
 for(const [i,block] of diff.entries()){const [lo,hi]=block[side];if(hi<=lo)continue;if(lo>cursor)fragments.push(chars.slice(cursor,lo).join(''));fragments.push(<mark key={i} className={changes&&block.kind!=='equal'?'changed':'shared'}>{chars.slice(lo,hi).join('')}</mark>);cursor=hi;}
 fragments.push(chars.slice(cursor).join(''));
 return <article className="passage"><div className="passage-top"><span className="source-label">SOURCE {side.toUpperCase()}</span><a href={passage.source_url} target="_blank" rel="noreferrer" aria-label={`Open ${passage.title} source`}><ExternalLink size={15}/></a></div><h3>{passage.title}</h3><div className="passage-ref">{passage.reference || 'Selected passage'}</div><div className="passage-text"><span className="context">{passage.before}</span><span className="match-text">{fragments}</span><span className="context">{passage.after}</span></div><div className="offsets">Characters {passage.start.toLocaleString()}–{passage.end.toLocaleString()} <span>End exclusive</span></div></article>
}
function App(){
 const [docs,setDocs]=useState<Doc[]>([]),[stats,setStats]=useState<Stats|null>(null),[rows,setRows]=useState<Parallel[]>([]),[total,setTotal]=useState(0);
 const [filters,setFilters]=useState(initialFilters),[query,setQuery]=useState(''),[page,setPage]=useState(0),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Detail|null>(null);
 const [view,setView]=useState<'explore'|'corpus'|'method'|'semantic'>('explore'),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[saving,setSaving]=useState(false);
 const [note,setNote]=useState(''),[changes,setChanges]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0),[starting,setStarting]=useState(false);
 const dirty=!!detail&&note!==detail.note;const dirtyRef=useRef(false);dirtyRef.current=dirty;
 const listGeneration=useRef(0);const requestedSelection=useRef(new URLSearchParams(location.search).get('parallel')||'');
 const search=new URLSearchParams({...filters,limit:'24',offset:String(page*24)}).toString();
 const refreshStats=useCallback(async()=>{try{setStats(await api<Stats>('/api/stats'))}catch(e){setError((e as Error).message)}},[]);
 useEffect(()=>{Promise.all([api<Doc[]>('/api/documents'),api<Stats>('/api/stats')]).then(([d,s])=>{setDocs(d);setStats(s)}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{const t=setTimeout(()=>{setFilters(f=>({...f,q:query}));setPage(0)},250);return()=>clearTimeout(t)},[query]);
 useEffect(()=>{const controller=new AbortController();const generation=++listGeneration.current;setLoading(true);
 api<{items:Parallel[];total:number}>('/api/parallels?'+search,{signal:controller.signal}).then(result=>{if(generation!==listGeneration.current)return;setRows(result.items);setTotal(result.total);setSelected(previous=>{const permalink=requestedSelection.current;requestedSelection.current='';if(permalink)return permalink;return result.items.some(r=>r.id===previous)?previous:(result.items[0]?.id||'')})}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(generation===listGeneration.current)setLoading(false)});
 return()=>controller.abort()},[search,revision]);
 useEffect(()=>{if(!selected){setDetail(null);return}const controller=new AbortController();setDetail(null);setDetailLoading(true);
 api<Detail>('/api/parallels/'+selected,{signal:controller.signal}).then(d=>{setDetail(d);setNote(d.note);history.replaceState(null,'','?parallel='+selected)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setDetailLoading(false)});return()=>controller.abort()},[selected]);
 const running=!!stats?.progress.running;
 useEffect(()=>{if(!running)return;const interval=setInterval(async()=>{try{const s=await api<Stats>('/api/stats');setStats(s);if(!s.progress.running){setRevision(x=>x+1);setStarting(false);if(s.run?.status==='failed')setError(s.run.error);else setNotice('Analysis complete. Existing review decisions were preserved.')}}catch(e){setError((e as Error).message)}},1000);return()=>clearInterval(interval)},[running]);
 useEffect(()=>{function unload(e:BeforeUnloadEvent){if(dirtyRef.current){e.preventDefault()}}window.addEventListener('beforeunload',unload);return()=>window.removeEventListener('beforeunload',unload)},[]);
 function canLeave(){if(saving)return false;return !dirtyRef.current||confirm('Discard your unsaved review note?')}
 function changeFilter(key:keyof typeof filters,value:string){if(!canLeave())return;setNote(detail?.note||'');setFilters(f=>({...f,[key]:value}));setPage(0)}
 function select(id:string){if(id===selected||!canLeave())return;setSelected(id);setNotice('')}
 async function save(status:ReviewStatus){if(!detail||saving)return;setSaving(true);setError('');try{await api('/api/parallels/'+detail.id+'/review',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,note})});setDetail({...detail,status,note});dirtyRef.current=false;setRows(r=>r.map(p=>p.id===detail.id?{...p,status,note}:p));setNotice('Review saved.');await refreshStats();if(filters.status&&filters.status!==status)setRevision(x=>x+1)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 async function rerun(){if(!canLeave())return;setStarting(true);setError('');setNotice('');try{await api('/api/analysis',{method:'POST'});await refreshStats()}catch(e){setError((e as Error).message);setStarting(false)}}
 function reset(){if(!canLeave())return;setQuery('');setFilters(initialFilters);setPage(0)}
 const reviewed=(stats?.counts.accepted||0)+(stats?.counts.rejected||0);
 return <div className="app-shell">
 <aside className="sidebar"><a className="brand" href="/" aria-label="Text Parallels Explorer home"><span className="brand-icon"><Layers3 size={24}/></span><span>Text Parallels<span className="brand-sub">EXPLORER</span></span></a><div className="workspace-label">RESEARCH WORKSPACE</div><nav aria-label="Main navigation">{([['explore','Parallels',BookOpen],['semantic','Semantic suggestions',FlaskConical],['corpus','Corpus',Layers3],['method','Method & runs',FlaskConical]] as const).map(([id,label,Icon])=><button key={id} className={view===id?'nav-item active':'nav-item'} onClick={()=>{if(canLeave())setView(id)}}><Icon size={19}/>{label}{id==='explore'&&stats?<span className="nav-count">{stats.counts.total}</span>:null}</button>)}</nav><div className="sidebar-bottom"><div className="corpus-stamp"><span className="tiny-label">ACTIVE COLLECTION</span><strong>The Synoptic Gospels</strong><span>3 documents · Public domain</span></div><div className="local-label"><span className="local-dot"/>Local research workspace</div></div></aside>
 <main className="main"><header className="topbar"><div className="breadcrumb">Workspace <span>/</span> {view==='explore'?'Parallels':view==='corpus'?'Corpus':view==='semantic'?'Semantic suggestions':'Method & runs'}</div><span className="edition-label">WORLD ENGLISH BIBLE CLASSIC</span></header>
 <section className="page-head"><div><div className="eyebrow">{view==='explore'?'DISCOVER & REVIEW':'COLLECTION & ANALYSIS'}</div><h1>{view==='explore'?'Textual parallels':view==='corpus'?'The source collection':view==='semantic'?'Semantic suggestions':'How matches are found'}</h1><p>{view==='explore'?'Compare shared passages. Keep the context. Record your judgment.':view==='corpus'?'Three complete texts, bundled with provenance and verse references.':view==='semantic'?'Explore related wording with a small, local embedding model.':'An explainable process, from shared words to aligned passages.'}</p></div><div className="head-actions">{view==='explore'?<a className="button secondary" href={'/api/export.csv?'+new URLSearchParams(filters)}><Download size={16}/>Export CSV</a>:null}<button className="button primary" onClick={rerun} disabled={running||starting}>{running||starting?<LoaderCircle className="spin" size={16}/>:<RefreshCw size={16}/>} {running?`Analyzing ${stats?.progress.completed_pairs}/${stats?.progress.total_pairs} pairs`:starting?'Starting…':'Run analysis'}</button></div></section>
 {error?<div className="alert error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>:null}{notice?<div className="alert success" role="status"><CheckCheck size={17}/>{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notification"><X size={16}/></button></div>:null}
 {view==='explore'?<><section className="metrics" aria-label="Collection statistics"><div><span>PARALLELS FOUND</span><strong>{stats?.counts.total?.toLocaleString()??'—'}</strong><small>Across all 3 document pairs</small></div><div><span>MATCH BREAKDOWN</span><strong>{stats?.counts.exact??'—'} <em>exact</em> <b>/</b> {stats?.counts.near??'—'} <em>near</em></strong><small>Normalized word sequences</small></div><div><span>REVIEW PROGRESS</span><strong>{reviewed} <em>of {stats?.counts.total??'—'}</em></strong><div className="progress-track"><div style={{width:`${stats?.counts.total?100*reviewed/stats.counts.total:0}%`}}/></div></div></section>
 <section className="filters" aria-label="Filter parallels"><div className="search-field"><Search size={17}/><input aria-label="Search passages" placeholder="Search passage text…" value={query} onChange={e=>{if(canLeave()){setNote(detail?.note||'');setQuery(e.target.value)}}}/></div><label><span>Documents</span><select aria-label="Document pair" value={filters.pair} onChange={e=>changeFilter('pair',e.target.value)}><option value="">All document pairs</option>{docs.flatMap((a,i)=>docs.slice(i+1).map(b=><option key={a.id+b.id} value={[a.id,b.id].sort().join(',')}>{a.title} & {b.title}</option>))}</select></label><label><span>Match type</span><select aria-label="Match type" value={filters.kind} onChange={e=>changeFilter('kind',e.target.value)}><option value="">All types</option><option value="exact">Exact match</option><option value="near">Near match</option></select></label><label><span>Review status</span><select aria-label="Review status" value={filters.status} onChange={e=>changeFilter('status',e.target.value)}><option value="">All statuses</option><option value="pending">Pending</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option></select></label><label className="score-filter"><span>Min. similarity</span><select aria-label="Min. similarity" value={filters.min_score} onChange={e=>changeFilter('min_score',e.target.value)}><option value="0">Any score</option><option value="0.75">75%</option><option value="0.85">85%</option><option value="0.95">95%</option><option value="1">100%</option></select></label><label><span>Min. length</span><select aria-label="Min. length" value={filters.min_words} onChange={e=>changeFilter('min_words',e.target.value)}><option value="0">Any length</option><option value="20">20 words</option><option value="40">40 words</option><option value="80">80 words</option></select></label></section>
 <div className="explorer"><section className="result-panel"><div className="result-heading"><span><ListFilter size={16}/><strong>{total}</strong> results</span><label className="sort-control"><span className="sr-only">Sort results</span><select aria-label="Sort results" value={filters.sort} onChange={e=>changeFilter('sort',e.target.value)}><option value="score">Highest similarity</option><option value="length">Longest passage</option><option value="position">Source position</option></select></label></div><div className="result-list" aria-busy={loading}>{loading?<div className="empty-state"><LoaderCircle className="spin"/>Loading parallels…</div>:rows.length?rows.map((r,i)=><button className={`result-card ${selected===r.id?'selected':''}`} key={r.id} onClick={()=>select(r.id)} aria-label={`${r.title_a} and ${r.title_b}, ${r.kind} match, ${percent(r.score)}`} aria-pressed={selected===r.id}><div className="result-card-top"><span className="result-number">{String(page*24+i+1).padStart(2,'0')}</span><Badge kind={r.kind}/><strong className="similarity">{percent(r.score)}</strong></div><h3>{r.title_a}<span> / </span>{r.title_b}</h3><p>{r.excerpt_a}{Array.from(r.excerpt_a).length>=180?'…':''}</p><div className="result-card-bottom"><span>{Math.min(r.words_a,r.words_b)} words</span><span className={`review-dot ${r.status}`}>{r.status==='accepted'?<Check size={12}/>:r.status==='rejected'?<X size={12}/>:null}{r.status}</span></div></button>):<div className="empty-state"><Search size={30}/><strong>No matching passages</strong><p>Try a lower similarity or a different filter.</p><button className="button secondary" onClick={reset}>Clear filters</button></div>}</div><div className="pagination"><span>{total?`${page*24+1}–${Math.min((page+1)*24,total)} of ${total}`:'0 results'}</span><div><button aria-label="Previous page" disabled={page===0||loading} onClick={()=>{if(canLeave())setPage(p=>p-1)}}><ChevronLeft size={17}/></button><button aria-label="Next page" disabled={(page+1)*24>=total||loading} onClick={()=>{if(canLeave())setPage(p=>p+1)}}><ChevronRight size={17}/></button></div></div></section>
 <section className="comparison-panel" aria-label="Passage comparison" aria-busy={detailLoading}>{detailLoading?<div className="empty-state"><LoaderCircle className="spin"/>Opening source passages…</div>:detail?<><div className="comparison-heading"><div><div className="tiny-label">PASSAGE COMPARISON</div><h2>{detail.passages[0].title} <span>&</span> {detail.passages[1].title}</h2></div><Badge kind={detail.status}/></div><div className="comparison-tools"><div className="legend"><span><i className="shared-key"/>Shared words</span>{changes?<span><i className="changed-key"/>Differences</span>:null}</div><label className="checkbox-label"><input type="checkbox" checked={changes} onChange={e=>setChanges(e.target.checked)}/>Show differences</label></div><div className="passage-grid">{detail.passages.map((p,i)=><PassageView key={i} passage={p} diff={detail.diff} side={i===0?'a':'b'} changes={changes}/>)}</div><div className="evidence"><SlidersHorizontal size={17}/><div><strong>{percent(detail.score)} word similarity</strong><span>{detail.words_a} / {detail.words_b} words · {detail.edit_distance} word edits · {detail.kind==='exact'?(detail.raw_exact?'Identical original text':'Identical after case and punctuation normalization'):detail.method==='skip-seed-local-alignment'?'Ordered word anchors with bounded skips and local alignment':'Shared 3-word anchors with local alignment'}</span></div></div><div className="review-section"><div className="review-heading"><h3>Researcher review</h3><span>{dirty?'Unsaved changes':'Saved to this workspace'}</span></div><label className="sr-only" htmlFor="review-note">Review note</label><textarea id="review-note" maxLength={5000} placeholder="Add a note about this parallel…" value={note} onChange={e=>setNote(e.target.value)} disabled={saving}/><div className="review-actions"><div><button className="button accept" onClick={()=>save('accepted')} disabled={saving}><Check size={16}/>Accept</button><button className="button secondary" onClick={()=>save('rejected')} disabled={saving}><X size={16}/>Reject</button><button className="text-button" onClick={()=>save('pending')} disabled={saving}>Mark pending</button></div><button className="button secondary" onClick={()=>save(detail.status)} disabled={saving||!dirty}>{saving?<LoaderCircle className="spin" size={15}/>:null}Save note</button></div></div></>:<div className="empty-state"><BookOpen size={32}/><strong>Select a parallel to compare</strong><p>Source text and review controls will appear here.</p></div>}</section></div></>:null}
 {view==='semantic'?<SemanticView/>:null}
 {view==='corpus'?<section className="info-panel"><div className="section-title"><BookOpen size={21}/><h2>Complete source texts</h2></div><div className="document-grid">{docs.map(d=><article className="document-card" key={d.id}><span className="source-label">PUBLIC DOMAIN</span><h3>{d.title}</h3><p>{d.edition}</p><dl><div><dt>Words</dt><dd>{d.word_count.toLocaleString()}</dd></div><div><dt>Characters</dt><dd>{d.characters.toLocaleString()}</dd></div></dl><a className="button secondary" href={d.source_url} target="_blank" rel="noreferrer">Read original source<ExternalLink size={14}/></a></article>)}</div><div className="provenance"><h3>Provenance & preparation</h3><p>The collection contains the complete Gospels of Matthew, Mark, and Luke from eBible.org's World English Bible Classic. Verse text is preserved; navigation, headings, verse numbers, and footnotes are excluded. Whitespace is standardized when building the bundled text files. Verse references are stored separately.</p><p>The translation is dedicated to the public domain. Each bundled document has a SHA-256 checksum. Detection operates on the bundled text, so every result can be traced to its exact source span.</p><a href="https://ebible.org/eng-web/copyright.htm" target="_blank" rel="noreferrer">Read the public-domain statement <ExternalLink size={14}/></a></div></section>:null}
 {view==='method'?<section className="info-panel"><div className="method-steps">{[['01','Preserve the source','Each word retains its original character range. Case, Unicode variants, and punctuation are normalized for comparison.'],['02','Find shared anchors','An index finds shared triples, either consecutive or allowing one intervening word per step. Ordered anchors identify candidate regions; frequent anchors are skipped.'],['03','Align locally','Local sequence alignment allows changed, added, and omitted words. Exact runs are also extended independently.'],['04','Score & review','Word edit distance measures similarity. Short, weak, and redundant matches are filtered before researcher review.']].map(([n,title,text])=><div className="method-step" key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></div>)}</div><div className="method-details"><div><h3>What the score means</h3><p>Similarity = 1 − word edit distance ÷ the longer passage length. A score measures wording similarity; it is not a probability of borrowing or a claim of historical dependence.</p><h3>Known boundaries</h3><p>Paraphrases without shared ordered word triples can be missed. Skip anchors allow at most one intervening word per step and do not lower the score threshold. Local alignment may trim changed edges. Frequent formulaic language can produce incidental matches. Researchers make the final decision.</p></div><div><h3>Last analysis</h3><p>Version <code>{stats?.algorithm}</code></p><p>{stats?.run?`Run #${stats.run.id} · ${stats.run.status} · ${stats.run.duration_seconds??'—'} seconds`:'No completed run'}</p><p>Re-running publishes results atomically and preserves reviews for the same passage ranges.</p></div></div><h3 className="run-title">Document pair coverage</h3><div className="table-scroll"><table><thead><tr><th>Document pair</th><th>Anchors (consecutive / skip)</th><th>Candidate regions</th><th>Parallels</th><th>Time</th></tr></thead><tbody>{stats?.run?.pairs.map(p=><tr key={p.document_a+p.document_b}><td className="capitalize">{p.document_a} / {p.document_b}</td><td>{(p.contiguous_seeds??p.seeds).toLocaleString()} / {(p.skip_seeds??0).toLocaleString()}</td><td>{p.candidate_windows.toLocaleString()}</td><td>{p.matches}</td><td>{p.duration_seconds}s</td></tr>)}</tbody></table></div></section>:null}
 <footer className="page-footer"><span>Text Parallels Explorer</span><span>Exact and near matches · Original-source offsets · Persistent review</span></footer></main></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
