import { useEffect, useState } from 'react';

type Suggestion={id:string;document_a:string;document_b:string;reference_a:string;reference_b:string;text_a:string;text_b:string;start_a:number;end_a:number;start_b:number;end_b:number;score:number;model:string;model_revision:string;status:'pending'|'accepted'|'rejected';note:string};
export default function SemanticView(){
 const [rows,setRows]=useState<Suggestion[]>([]),[total,setTotal]=useState(0),[selected,setSelected]=useState('');
 const [pair,setPair]=useState(''),[score,setScore]=useState('.65'),[status,setStatus]=useState(''),[page,setPage]=useState(0);
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 const params=new URLSearchParams({pair,min_score:score,status,limit:'24',offset:String(page*24)}).toString();
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');
 fetch('/api/semantic?'+params,{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('Unable to load semantic suggestions');return r.json()}).then(r=>{setRows(r.items);setTotal(r.total);setSelected(id=>r.items.some((m:Suggestion)=>m.id===id)?id:r.items[0]?.id||'')}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});
 return()=>controller.abort()},[params,revision]);
 const detail=rows.find(m=>m.id===selected);
 async function review(next:Suggestion['status']){if(!detail||saving)return;setSaving(true);setError('');try{
 const response=await fetch('/api/semantic/'+detail.id+'/review',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:next,note:detail.note})});
 if(!response.ok)throw new Error('Unable to save semantic review');setRows(r=>r.map(m=>m.id===detail.id?{...m,status:next}:m));if(status&&status!==next)setRevision(n=>n+1)
 }catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 return <>
 <section className="info-panel semantic-intro"><h2>Find related passages with different wording</h2><p>One or two adjacent verses are encoded with the open-source <strong>paraphrase-MiniLM-L6-v2</strong> model. Each passage keeps its strongest mutual match in another document, above cosine 0.65. Suggestions already substantially covered by lexical results are excluded.</p><p>These suggestions are computed locally during workspace preparation. <strong>Run analysis</strong> refreshes lexical matches and checks the saved semantic results. Cosine is a ranking score, not a percentage or a probability. Similar wording can hide different facts, negation, or reversed roles.</p></section>
 {error?<div className="alert error" role="alert">{error}</div>:null}
 <section className="filters" aria-label="Filter semantic suggestions"><label><span>Documents</span><select aria-label="Semantic document pair" value={pair} disabled={saving} onChange={e=>{setPair(e.target.value);setPage(0)}}><option value="">All document pairs</option><option value="luke,mark">Luke & Mark</option><option value="luke,matthew">Luke & Matthew</option><option value="mark,matthew">Mark & Matthew</option></select></label><label><span>Minimum cosine</span><select aria-label="Minimum cosine" value={score} disabled={saving} onChange={e=>{setScore(e.target.value);setPage(0)}}>{['.65','.7','.8','.9'].map(v=><option key={v} value={v}>{Number(v).toFixed(2)}</option>)}</select></label><label><span>Review status</span><select aria-label="Semantic review status" value={status} disabled={saving} onChange={e=>{setStatus(e.target.value);setPage(0)}}><option value="">All statuses</option><option value="pending">Pending</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option></select></label></section>
 <div className="explorer"><section className="result-panel"><div className="result-heading"><strong>{total} semantic suggestions</strong></div><div className="result-list" aria-busy={loading}>{loading?<div className="empty-state">Loading suggestions…</div>:rows.length?rows.map(m=><button className={'result-card '+(selected===m.id?'selected':'')} key={m.id} disabled={saving} onClick={()=>setSelected(m.id)} aria-pressed={selected===m.id}><div className="result-card-top"><span className="badge near">Semantic suggestion</span><strong>cos {m.score.toFixed(3)}</strong></div><h3 className="capitalize">{m.document_a} / {m.document_b}</h3><p>{m.text_a.slice(0,180)}</p><div className="result-card-bottom"><span>{m.reference_a} / {m.reference_b}</span><span className={'review-dot '+m.status}>{m.status}</span></div></button>):<div className="empty-state">No semantic suggestions for these filters.</div>}</div><div className="pagination"><span>{total?`${page*24+1}–${Math.min((page+1)*24,total)} of ${total}`:'0 results'}</span><div><button aria-label="Previous semantic page" disabled={!page||loading||saving} onClick={()=>setPage(p=>p-1)}>←</button><button aria-label="Next semantic page" disabled={(page+1)*24>=total||loading||saving} onClick={()=>setPage(p=>p+1)}>→</button></div></div></section>
 <section className="comparison-panel" aria-label="Semantic passage comparison">{!loading&&detail?<><div className="comparison-heading"><div><div className="tiny-label">SEMANTIC SUGGESTION</div><h2 className="capitalize">{detail.document_a} & {detail.document_b}</h2></div><span className={'badge '+detail.status}>{detail.status}</span></div><div className="passage-grid">{(['a','b'] as const).map(side=><article className="passage" key={side}><span className="source-label">SOURCE {side.toUpperCase()}</span><h3 className="capitalize">{detail['document_'+side as 'document_a'|'document_b']}</h3><div className="passage-ref">{detail['reference_'+side as 'reference_a'|'reference_b']}</div><div className="passage-text"><mark className="changed">{detail['text_'+side as 'text_a'|'text_b']}</mark></div><div className="offsets">Characters {detail['start_'+side as 'start_a'|'start_b']}–{detail['end_'+side as 'end_a'|'end_b']} · End exclusive</div></article>)}</div><div className="evidence"><div><strong>Cosine similarity {detail.score.toFixed(3)}</strong><span>Highlighted verse windows are candidate regions, not aligned identical words.</span></div></div><div className="review-section"><h3>Researcher review</h3><div className="review-actions"><button className="button accept" disabled={saving} onClick={()=>review('accepted')}>Accept suggestion</button><button className="button secondary" disabled={saving} onClick={()=>review('rejected')}>Reject suggestion</button><button className="text-button" disabled={saving} onClick={()=>review('pending')}>Mark suggestion pending</button></div><p>Reviews persist across restarts and semantic cache imports.</p></div></>:<div className="empty-state">Select a suggestion to compare.</div>}</section></div>
 </>
}
